#!/usr/bin/env python3
"""Generate lexicon.json from LEXICON.md.

LEXICON.md is the source of truth. Run this after editing it:

    python3 tools/build_lexicon_json.py

Structure recognised in the markdown:

    # <roman>. <part title>      a part
    ## <situation title>         a situation within the part
    *<use note>*                 the italic line under a situation
    > <saying>                   a saying, possibly wrapped over lines

A saying wholly in bold is canon (one of the three seed sayings). In the
call-and-answer situation, `**<call>** — *<answer>*` is split into its
two halves.
"""

import json
import re
import unicodedata
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SOURCE = ROOT / "LEXICON.md"
TARGET = ROOT / "lexicon.json"

ROMAN = {"I": 1, "II": 2, "III": 3, "IV": 4, "V": 5, "VI": 6, "VII": 7,
         "VIII": 8, "IX": 9, "X": 10, "XI": 11, "XII": 12, "XIII": 13}

PART_RE = re.compile(r"^# ([IVX]+)\. (.+)$")
SITUATION_RE = re.compile(r"^## (.+)$")
USE_NOTE_RE = re.compile(r"^\*(.+)\*$")
SAYING_RE = re.compile(r"^> (.*)$")
CALL_ANSWER_RE = re.compile(r"^\*\*(.+?)\*\* — \*(.+?)\*$")
FULLY_BOLD_RE = re.compile(r"^\*\*(.+)\*\*$")


def slug(text):
    text = unicodedata.normalize("NFKD", text).encode("ascii", "ignore").decode()
    return re.sub(r"-+", "-", re.sub(r"[^a-z0-9]+", "-", text.lower())).strip("-")


def parse(markdown):
    parts, part, situation, pending = [], None, None, []

    def flush():
        """Attach the accumulated blockquote lines as one saying."""
        if not pending or situation is None:
            pending.clear()
            return
        text = " ".join(pending).strip()
        pending.clear()
        if not text:
            return
        entry = {
            "id": f"{slug(part['title'])}.{slug(situation['title'])}.{len(situation['sayings']) + 1}",
            "text": text,
        }
        call_answer = CALL_ANSWER_RE.match(text)
        bold = FULLY_BOLD_RE.match(text)
        if call_answer:
            entry["text"] = f"{call_answer.group(1)} — {call_answer.group(2)}"
            entry["call"] = call_answer.group(1)
            entry["answer"] = call_answer.group(2)
        elif bold:
            entry["text"] = bold.group(1)
            entry["canon"] = True
        situation["sayings"].append(entry)

    for line in markdown.splitlines():
        saying = SAYING_RE.match(line)
        if saying:
            content = saying.group(1).strip()
            if content:
                # A blank "> " line, or a new "> " after text, starts a new saying.
                if pending and not line.startswith(">  "):
                    if pending and pending[-1].endswith((".", "!", "?", "*")):
                        flush()
                pending.append(content)
            continue
        flush()

        part_match = PART_RE.match(line)
        if part_match:
            part = {"number": ROMAN[part_match.group(1)],
                    "title": part_match.group(2),
                    "slug": slug(part_match.group(2)),
                    "situations": []}
            parts.append(part)
            situation = None
            continue

        situation_match = SITUATION_RE.match(line)
        if situation_match and part is not None:
            situation = {"title": situation_match.group(1),
                         "slug": slug(situation_match.group(1)),
                         "use_note": None,
                         "sayings": []}
            part["situations"].append(situation)
            continue

        note = USE_NOTE_RE.match(line.strip())
        if note and situation is not None and situation["use_note"] is None:
            situation["use_note"] = note.group(1)

    flush()
    return parts


def main():
    parts = parse(SOURCE.read_text(encoding="utf-8"))

    flat = []
    for part in parts:
        for situation in part["situations"]:
            for saying in situation["sayings"]:
                row = dict(saying)
                row.update({
                    "part": part["title"],
                    "part_number": part["number"],
                    "situation": situation["title"],
                    "use_note": situation["use_note"],
                })
                flat.append(row)

    document = {
        "title": "Lexicon — Elven Sayings",
        "source": "LEXICON.md",
        "note": "Generated by tools/build_lexicon_json.py. Edit LEXICON.md, not this file.",
        "counts": {
            "sayings": len(flat),
            "situations": sum(len(p["situations"]) for p in parts),
            "parts": len(parts),
        },
        "parts": [
            {"number": p["number"], "title": p["title"], "slug": p["slug"],
             "situations": [
                 {"title": s["title"], "slug": s["slug"], "use_note": s["use_note"],
                  "count": len(s["sayings"])}
                 for s in p["situations"]
             ]}
            for p in parts
        ],
        "sayings": flat,
    }

    TARGET.write_text(json.dumps(document, indent=2, ensure_ascii=False) + "\n",
                      encoding="utf-8")
    print(f"{TARGET.name}: {document['counts']['sayings']} sayings, "
          f"{document['counts']['situations']} situations, "
          f"{document['counts']['parts']} parts")


if __name__ == "__main__":
    main()
